// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package legacy

import (
	"context"

	"github.com/ipni/go-libipni/find/model"
	"github.com/multiformats/go-multicodec"
	"github.com/multiformats/go-multihash"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaimsFinder creates a new instance of MockClaimsFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaimsFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaimsFinder {
	mock := &MockClaimsFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaimsFinder is an autogenerated mock type for the ClaimsFinder type
type MockClaimsFinder struct {
	mock.Mock
}

type MockClaimsFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaimsFinder) EXPECT() *MockClaimsFinder_Expecter {
	return &MockClaimsFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockClaimsFinder
func (_mock *MockClaimsFinder) Find(ctx context.Context, contentHash multihash.Multihash, targetClaims []multicodec.Code) ([]model.ProviderResult, error) {
	ret := _mock.Called(ctx, contentHash, targetClaims)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.ProviderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, []multicodec.Code) ([]model.ProviderResult, error)); ok {
		return returnFunc(ctx, contentHash, targetClaims)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, []multicodec.Code) []model.ProviderResult); ok {
		r0 = returnFunc(ctx, contentHash, targetClaims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProviderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, multihash.Multihash, []multicodec.Code) error); ok {
		r1 = returnFunc(ctx, contentHash, targetClaims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaimsFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockClaimsFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - contentHash multihash.Multihash
//   - targetClaims []multicodec.Code
func (_e *MockClaimsFinder_Expecter) Find(ctx interface{}, contentHash interface{}, targetClaims interface{}) *MockClaimsFinder_Find_Call {
	return &MockClaimsFinder_Find_Call{Call: _e.mock.On("Find", ctx, contentHash, targetClaims)}
}

func (_c *MockClaimsFinder_Find_Call) Run(run func(ctx context.Context, contentHash multihash.Multihash, targetClaims []multicodec.Code)) *MockClaimsFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		var arg2 []multicodec.Code
		if args[2] != nil {
			arg2 = args[2].([]multicodec.Code)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClaimsFinder_Find_Call) Return(providerResults []model.ProviderResult, err error) *MockClaimsFinder_Find_Call {
	_c.Call.Return(providerResults, err)
	return _c
}

func (_c *MockClaimsFinder_Find_Call) RunAndReturn(run func(ctx context.Context, contentHash multihash.Multihash, targetClaims []multicodec.Code) ([]model.ProviderResult, error)) *MockClaimsFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}
