// Code generated by mockery v2.53.4. DO NOT EDIT.

package legacy

import (
	context "context"

	model "github.com/ipni/go-libipni/find/model"
	mock "github.com/stretchr/testify/mock"

	multicodec "github.com/multiformats/go-multicodec"

	multihash "github.com/multiformats/go-multihash"
)

// MockClaimsFinder is an autogenerated mock type for the ClaimsFinder type
type MockClaimsFinder struct {
	mock.Mock
}

type MockClaimsFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaimsFinder) EXPECT() *MockClaimsFinder_Expecter {
	return &MockClaimsFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, contentHash, targetClaims
func (_m *MockClaimsFinder) Find(ctx context.Context, contentHash multihash.Multihash, targetClaims []multicodec.Code) ([]model.ProviderResult, error) {
	ret := _m.Called(ctx, contentHash, targetClaims)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.ProviderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash, []multicodec.Code) ([]model.ProviderResult, error)); ok {
		return rf(ctx, contentHash, targetClaims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash, []multicodec.Code) []model.ProviderResult); ok {
		r0 = rf(ctx, contentHash, targetClaims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProviderResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, multihash.Multihash, []multicodec.Code) error); ok {
		r1 = rf(ctx, contentHash, targetClaims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClaimsFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockClaimsFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - contentHash multihash.Multihash
//   - targetClaims []multicodec.Code
func (_e *MockClaimsFinder_Expecter) Find(ctx interface{}, contentHash interface{}, targetClaims interface{}) *MockClaimsFinder_Find_Call {
	return &MockClaimsFinder_Find_Call{Call: _e.mock.On("Find", ctx, contentHash, targetClaims)}
}

func (_c *MockClaimsFinder_Find_Call) Run(run func(ctx context.Context, contentHash multihash.Multihash, targetClaims []multicodec.Code)) *MockClaimsFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash), args[2].([]multicodec.Code))
	})
	return _c
}

func (_c *MockClaimsFinder_Find_Call) Return(_a0 []model.ProviderResult, _a1 error) *MockClaimsFinder_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClaimsFinder_Find_Call) RunAndReturn(run func(context.Context, multihash.Multihash, []multicodec.Code) ([]model.ProviderResult, error)) *MockClaimsFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClaimsFinder creates a new instance of MockClaimsFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaimsFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaimsFinder {
	mock := &MockClaimsFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
