// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package extmocks

import (
	"context"

	"github.com/ipni/go-libipni/find/model"
	"github.com/multiformats/go-multihash"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIpniFinder creates a new instance of MockIpniFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIpniFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIpniFinder {
	mock := &MockIpniFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIpniFinder is an autogenerated mock type for the Finder type
type MockIpniFinder struct {
	mock.Mock
}

type MockIpniFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIpniFinder) EXPECT() *MockIpniFinder_Expecter {
	return &MockIpniFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockIpniFinder
func (_mock *MockIpniFinder) Find(context1 context.Context, multihash1 multihash.Multihash) (*model.FindResponse, error) {
	ret := _mock.Called(context1, multihash1)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *model.FindResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash) (*model.FindResponse, error)); ok {
		return returnFunc(context1, multihash1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash) *model.FindResponse); ok {
		r0 = returnFunc(context1, multihash1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FindResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, multihash.Multihash) error); ok {
		r1 = returnFunc(context1, multihash1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIpniFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockIpniFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - context1 context.Context
//   - multihash1 multihash.Multihash
func (_e *MockIpniFinder_Expecter) Find(context1 interface{}, multihash1 interface{}) *MockIpniFinder_Find_Call {
	return &MockIpniFinder_Find_Call{Call: _e.mock.On("Find", context1, multihash1)}
}

func (_c *MockIpniFinder_Find_Call) Run(run func(context1 context.Context, multihash1 multihash.Multihash)) *MockIpniFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIpniFinder_Find_Call) Return(findResponse *model.FindResponse, err error) *MockIpniFinder_Find_Call {
	_c.Call.Return(findResponse, err)
	return _c
}

func (_c *MockIpniFinder_Find_Call) RunAndReturn(run func(context1 context.Context, multihash1 multihash.Multihash) (*model.FindResponse, error)) *MockIpniFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}
