issue-845-fix: True
resolve-type-alias: False
with-expecter: True
inpackage: True
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/storacha/indexing-service/pkg/service/providerindex:
    interfaces:
      ContentToClaimsMapper:
      LegacyClaimsFinder:
  github.com/storacha/indexing-service/pkg/service/contentclaims:
    interfaces:
      Finder:
        config:
          filename: mock_ContentClaimsFinder.go
          mockname: MockContentClaimsFinder
  github.com/storacha/indexing-service/pkg/types:
    interfaces:
      ContentClaimsCache:
      ContentClaimsStore:
      ProviderStore:
  github.com/aws/aws-sdk-go-v2/service/dynamodb:
    interfaces:
      QueryAPIClient:
        config:
          inpackage: False
          dir: "pkg/internal/testutil/extmocks"
          outpkg: "extmocks"
          filename: mock_DynamoDBQueryClient.go
          mockname: MockDynamoDBQueryClient
  github.com/ipni/go-libipni/find/client:
    interfaces:
      Finder:
        config:
          inpackage: False
          dir: "pkg/internal/testutil/extmocks"
          outpkg: "extmocks"
          filename: mock_IpniFinder.go
          mockname: MockIpniFinder
  github.com/storacha/ipni-publisher/pkg/publisher:
    interfaces:
      Publisher:
        config:
          inpackage: False
          dir: "pkg/internal/testutil/extmocks"
          outpkg: "extmocks"
          filename: mock_IpniPublisher.go
          mockname: MockIpniPublisher
