issue-845-fix: True
resolve-type-alias: False
with-expecter: True
filename: "mock_{{.InterfaceName}}.go"
dir: "pkg/internal/testutil/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/storacha/indexing-service/pkg/service/blobindexlookup:
    interfaces:
      BlobIndexLookup:
  github.com/storacha/indexing-service/pkg/service/contentclaims:
    config:
      filename: "mock_ContentClaims{{.InterfaceName}}.go"
      mockname: "MockContentClaims{{.InterfaceName}}"
    interfaces:
      Finder:
      Service:
  github.com/storacha/indexing-service/pkg/service/providerindex:
    interfaces:
      ContentToClaimsMapper:
      LegacyClaimsFinder:
      ProviderIndex:
  github.com/storacha/indexing-service/pkg/types:
    interfaces:
      ContentClaimsCache:
      ContentClaimsStore:
      ProviderStore:
  github.com/aws/aws-sdk-go-v2/service/dynamodb:
    interfaces:
      QueryAPIClient:
  github.com/ipni/go-libipni/find/client:
    interfaces:
      Finder:
  github.com/storacha/ipni-publisher/pkg/publisher:
    interfaces:
      Publisher:
