receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

exporters:
  otlp:
    endpoint: ${env:HONEYCOMB_OTLP_ENDPOINT}
    headers:
      "x-honeycomb-team": ${env:HONEYCOMB_API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
