// Code generated by mockery v2.50.0. DO NOT EDIT.

package providerindex

import (
	context "context"

	model "github.com/ipni/go-libipni/find/model"
	mock "github.com/stretchr/testify/mock"

	multihash "github.com/multiformats/go-multihash"
)

// MockLegacyClaimsFinder is an autogenerated mock type for the LegacyClaimsFinder type
type MockLegacyClaimsFinder struct {
	mock.Mock
}

type MockLegacyClaimsFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLegacyClaimsFinder) EXPECT() *MockLegacyClaimsFinder_Expecter {
	return &MockLegacyClaimsFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, contentHash
func (_m *MockLegacyClaimsFinder) Find(ctx context.Context, contentHash multihash.Multihash) ([]model.ProviderResult, error) {
	ret := _m.Called(ctx, contentHash)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.ProviderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) ([]model.ProviderResult, error)); ok {
		return rf(ctx, contentHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) []model.ProviderResult); ok {
		r0 = rf(ctx, contentHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProviderResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, multihash.Multihash) error); ok {
		r1 = rf(ctx, contentHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLegacyClaimsFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockLegacyClaimsFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - contentHash multihash.Multihash
func (_e *MockLegacyClaimsFinder_Expecter) Find(ctx interface{}, contentHash interface{}) *MockLegacyClaimsFinder_Find_Call {
	return &MockLegacyClaimsFinder_Find_Call{Call: _e.mock.On("Find", ctx, contentHash)}
}

func (_c *MockLegacyClaimsFinder_Find_Call) Run(run func(ctx context.Context, contentHash multihash.Multihash)) *MockLegacyClaimsFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash))
	})
	return _c
}

func (_c *MockLegacyClaimsFinder_Find_Call) Return(_a0 []model.ProviderResult, _a1 error) *MockLegacyClaimsFinder_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLegacyClaimsFinder_Find_Call) RunAndReturn(run func(context.Context, multihash.Multihash) ([]model.ProviderResult, error)) *MockLegacyClaimsFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLegacyClaimsFinder creates a new instance of MockLegacyClaimsFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLegacyClaimsFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLegacyClaimsFinder {
	mock := &MockLegacyClaimsFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
