// Code generated by mockery v2.50.0. DO NOT EDIT.

package contentclaims

import (
	context "context"

	ipld "github.com/ipld/go-ipld-prime"
	delegation "github.com/storacha/go-ucanto/core/delegation"

	mock "github.com/stretchr/testify/mock"

	url "net/url"
)

// MockContentClaimsService is an autogenerated mock type for the Service type
type MockContentClaimsService struct {
	mock.Mock
}

type MockContentClaimsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentClaimsService) EXPECT() *MockContentClaimsService_Expecter {
	return &MockContentClaimsService_Expecter{mock: &_m.Mock}
}

// Cache provides a mock function with given fields: ctx, claim
func (_m *MockContentClaimsService) Cache(ctx context.Context, claim delegation.Delegation) error {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for Cache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, delegation.Delegation) error); ok {
		r0 = rf(ctx, claim)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContentClaimsService_Cache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cache'
type MockContentClaimsService_Cache_Call struct {
	*mock.Call
}

// Cache is a helper method to define mock.On call
//   - ctx context.Context
//   - claim delegation.Delegation
func (_e *MockContentClaimsService_Expecter) Cache(ctx interface{}, claim interface{}) *MockContentClaimsService_Cache_Call {
	return &MockContentClaimsService_Cache_Call{Call: _e.mock.On("Cache", ctx, claim)}
}

func (_c *MockContentClaimsService_Cache_Call) Run(run func(ctx context.Context, claim delegation.Delegation)) *MockContentClaimsService_Cache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(delegation.Delegation))
	})
	return _c
}

func (_c *MockContentClaimsService_Cache_Call) Return(_a0 error) *MockContentClaimsService_Cache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContentClaimsService_Cache_Call) RunAndReturn(run func(context.Context, delegation.Delegation) error) *MockContentClaimsService_Cache_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, claim, fetchURL
func (_m *MockContentClaimsService) Find(ctx context.Context, claim ipld.Link, fetchURL *url.URL) (delegation.Delegation, error) {
	ret := _m.Called(ctx, claim, fetchURL)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 delegation.Delegation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ipld.Link, *url.URL) (delegation.Delegation, error)); ok {
		return rf(ctx, claim, fetchURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ipld.Link, *url.URL) delegation.Delegation); ok {
		r0 = rf(ctx, claim, fetchURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(delegation.Delegation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ipld.Link, *url.URL) error); ok {
		r1 = rf(ctx, claim, fetchURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContentClaimsService_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockContentClaimsService_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - claim ipld.Link
//   - fetchURL *url.URL
func (_e *MockContentClaimsService_Expecter) Find(ctx interface{}, claim interface{}, fetchURL interface{}) *MockContentClaimsService_Find_Call {
	return &MockContentClaimsService_Find_Call{Call: _e.mock.On("Find", ctx, claim, fetchURL)}
}

func (_c *MockContentClaimsService_Find_Call) Run(run func(ctx context.Context, claim ipld.Link, fetchURL *url.URL)) *MockContentClaimsService_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ipld.Link), args[2].(*url.URL))
	})
	return _c
}

func (_c *MockContentClaimsService_Find_Call) Return(_a0 delegation.Delegation, _a1 error) *MockContentClaimsService_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContentClaimsService_Find_Call) RunAndReturn(run func(context.Context, ipld.Link, *url.URL) (delegation.Delegation, error)) *MockContentClaimsService_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, claim
func (_m *MockContentClaimsService) Get(ctx context.Context, claim ipld.Link) (delegation.Delegation, error) {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 delegation.Delegation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ipld.Link) (delegation.Delegation, error)); ok {
		return rf(ctx, claim)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ipld.Link) delegation.Delegation); ok {
		r0 = rf(ctx, claim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(delegation.Delegation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ipld.Link) error); ok {
		r1 = rf(ctx, claim)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContentClaimsService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContentClaimsService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - claim ipld.Link
func (_e *MockContentClaimsService_Expecter) Get(ctx interface{}, claim interface{}) *MockContentClaimsService_Get_Call {
	return &MockContentClaimsService_Get_Call{Call: _e.mock.On("Get", ctx, claim)}
}

func (_c *MockContentClaimsService_Get_Call) Run(run func(ctx context.Context, claim ipld.Link)) *MockContentClaimsService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ipld.Link))
	})
	return _c
}

func (_c *MockContentClaimsService_Get_Call) Return(_a0 delegation.Delegation, _a1 error) *MockContentClaimsService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContentClaimsService_Get_Call) RunAndReturn(run func(context.Context, ipld.Link) (delegation.Delegation, error)) *MockContentClaimsService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, claim
func (_m *MockContentClaimsService) Publish(ctx context.Context, claim delegation.Delegation) error {
	ret := _m.Called(ctx, claim)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, delegation.Delegation) error); ok {
		r0 = rf(ctx, claim)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContentClaimsService_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockContentClaimsService_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - claim delegation.Delegation
func (_e *MockContentClaimsService_Expecter) Publish(ctx interface{}, claim interface{}) *MockContentClaimsService_Publish_Call {
	return &MockContentClaimsService_Publish_Call{Call: _e.mock.On("Publish", ctx, claim)}
}

func (_c *MockContentClaimsService_Publish_Call) Run(run func(ctx context.Context, claim delegation.Delegation)) *MockContentClaimsService_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(delegation.Delegation))
	})
	return _c
}

func (_c *MockContentClaimsService_Publish_Call) Return(_a0 error) *MockContentClaimsService_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContentClaimsService_Publish_Call) RunAndReturn(run func(context.Context, delegation.Delegation) error) *MockContentClaimsService_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContentClaimsService creates a new instance of MockContentClaimsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentClaimsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentClaimsService {
	mock := &MockContentClaimsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
