// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	"context"

	"github.com/ipni/go-libipni/find/model"
	"github.com/multiformats/go-multihash"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProviderStore creates a new instance of MockProviderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderStore {
	mock := &MockProviderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProviderStore is an autogenerated mock type for the ProviderStore type
type MockProviderStore struct {
	mock.Mock
}

type MockProviderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderStore) EXPECT() *MockProviderStore_Expecter {
	return &MockProviderStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockProviderStore
func (_mock *MockProviderStore) Add(ctx context.Context, key multihash.Multihash, values ...model.ProviderResult) (uint64, error) {
	// model.ProviderResult
	_va := make([]interface{}, len(values))
	for _i := range values {
		_va[_i] = values[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, ...model.ProviderResult) (uint64, error)); ok {
		return returnFunc(ctx, key, values...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, ...model.ProviderResult) uint64); ok {
		r0 = returnFunc(ctx, key, values...)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, multihash.Multihash, ...model.ProviderResult) error); ok {
		r1 = returnFunc(ctx, key, values...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockProviderStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - values ...model.ProviderResult
func (_e *MockProviderStore_Expecter) Add(ctx interface{}, key interface{}, values ...interface{}) *MockProviderStore_Add_Call {
	return &MockProviderStore_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx, key}, values...)...)}
}

func (_c *MockProviderStore_Add_Call) Run(run func(ctx context.Context, key multihash.Multihash, values ...model.ProviderResult)) *MockProviderStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		var arg2 []model.ProviderResult
		variadicArgs := make([]model.ProviderResult, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(model.ProviderResult)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProviderStore_Add_Call) Return(v uint64, err error) *MockProviderStore_Add_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockProviderStore_Add_Call) RunAndReturn(run func(ctx context.Context, key multihash.Multihash, values ...model.ProviderResult) (uint64, error)) *MockProviderStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Batch provides a mock function for the type MockProviderStore
func (_mock *MockProviderStore) Batch() ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Batch")
	}

	var r0 ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]
	if returnFunc, ok := ret.Get(0).(func() ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult])
		}
	}
	return r0
}

// MockProviderStore_Batch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Batch'
type MockProviderStore_Batch_Call struct {
	*mock.Call
}

// Batch is a helper method to define mock.On call
func (_e *MockProviderStore_Expecter) Batch() *MockProviderStore_Batch_Call {
	return &MockProviderStore_Batch_Call{Call: _e.mock.On("Batch")}
}

func (_c *MockProviderStore_Batch_Call) Run(run func()) *MockProviderStore_Batch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProviderStore_Batch_Call) Return(valueSetCacheBatcher ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]) *MockProviderStore_Batch_Call {
	_c.Call.Return(valueSetCacheBatcher)
	return _c
}

func (_c *MockProviderStore_Batch_Call) RunAndReturn(run func() ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]) *MockProviderStore_Batch_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type MockProviderStore
func (_mock *MockProviderStore) Members(ctx context.Context, key multihash.Multihash) ([]model.ProviderResult, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []model.ProviderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash) ([]model.ProviderResult, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash) []model.ProviderResult); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProviderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, multihash.Multihash) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProviderStore_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type MockProviderStore_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
func (_e *MockProviderStore_Expecter) Members(ctx interface{}, key interface{}) *MockProviderStore_Members_Call {
	return &MockProviderStore_Members_Call{Call: _e.mock.On("Members", ctx, key)}
}

func (_c *MockProviderStore_Members_Call) Run(run func(ctx context.Context, key multihash.Multihash)) *MockProviderStore_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProviderStore_Members_Call) Return(providerResults []model.ProviderResult, err error) *MockProviderStore_Members_Call {
	_c.Call.Return(providerResults, err)
	return _c
}

func (_c *MockProviderStore_Members_Call) RunAndReturn(run func(ctx context.Context, key multihash.Multihash) ([]model.ProviderResult, error)) *MockProviderStore_Members_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpirable provides a mock function for the type MockProviderStore
func (_mock *MockProviderStore) SetExpirable(ctx context.Context, key multihash.Multihash, expires bool) error {
	ret := _mock.Called(ctx, key, expires)

	if len(ret) == 0 {
		panic("no return value specified for SetExpirable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, bool) error); ok {
		r0 = returnFunc(ctx, key, expires)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProviderStore_SetExpirable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpirable'
type MockProviderStore_SetExpirable_Call struct {
	*mock.Call
}

// SetExpirable is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - expires bool
func (_e *MockProviderStore_Expecter) SetExpirable(ctx interface{}, key interface{}, expires interface{}) *MockProviderStore_SetExpirable_Call {
	return &MockProviderStore_SetExpirable_Call{Call: _e.mock.On("SetExpirable", ctx, key, expires)}
}

func (_c *MockProviderStore_SetExpirable_Call) Run(run func(ctx context.Context, key multihash.Multihash, expires bool)) *MockProviderStore_SetExpirable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProviderStore_SetExpirable_Call) Return(err error) *MockProviderStore_SetExpirable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProviderStore_SetExpirable_Call) RunAndReturn(run func(ctx context.Context, key multihash.Multihash, expires bool) error) *MockProviderStore_SetExpirable_Call {
	_c.Call.Return(run)
	return _c
}
