// Code generated by mockery v2.50.0. DO NOT EDIT.

package types

import (
	context "context"

	multihash "github.com/multiformats/go-multihash"
	mock "github.com/stretchr/testify/mock"
)

// MockNoProviderStore is an autogenerated mock type for the NoProviderStore type
type MockNoProviderStore struct {
	mock.Mock
}

type MockNoProviderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoProviderStore) EXPECT() *MockNoProviderStore_Expecter {
	return &MockNoProviderStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockNoProviderStore) Get(ctx context.Context, key multihash.Multihash) (struct{}, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 struct{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) (struct{}, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) struct{}); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(struct{})
	}

	if rf, ok := ret.Get(1).(func(context.Context, multihash.Multihash) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNoProviderStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockNoProviderStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
func (_e *MockNoProviderStore_Expecter) Get(ctx interface{}, key interface{}) *MockNoProviderStore_Get_Call {
	return &MockNoProviderStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockNoProviderStore_Get_Call) Run(run func(ctx context.Context, key multihash.Multihash)) *MockNoProviderStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash))
	})
	return _c
}

func (_c *MockNoProviderStore_Get_Call) Return(_a0 struct{}, _a1 error) *MockNoProviderStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNoProviderStore_Get_Call) RunAndReturn(run func(context.Context, multihash.Multihash) (struct{}, error)) *MockNoProviderStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expires
func (_m *MockNoProviderStore) Set(ctx context.Context, key multihash.Multihash, value struct{}, expires bool) error {
	ret := _m.Called(ctx, key, value, expires)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash, struct{}, bool) error); ok {
		r0 = rf(ctx, key, value, expires)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNoProviderStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockNoProviderStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - value struct{}
//   - expires bool
func (_e *MockNoProviderStore_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expires interface{}) *MockNoProviderStore_Set_Call {
	return &MockNoProviderStore_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expires)}
}

func (_c *MockNoProviderStore_Set_Call) Run(run func(ctx context.Context, key multihash.Multihash, value struct{}, expires bool)) *MockNoProviderStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash), args[2].(struct{}), args[3].(bool))
	})
	return _c
}

func (_c *MockNoProviderStore_Set_Call) Return(_a0 error) *MockNoProviderStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoProviderStore_Set_Call) RunAndReturn(run func(context.Context, multihash.Multihash, struct{}, bool) error) *MockNoProviderStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpirable provides a mock function with given fields: ctx, key, expires
func (_m *MockNoProviderStore) SetExpirable(ctx context.Context, key multihash.Multihash, expires bool) error {
	ret := _m.Called(ctx, key, expires)

	if len(ret) == 0 {
		panic("no return value specified for SetExpirable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash, bool) error); ok {
		r0 = rf(ctx, key, expires)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNoProviderStore_SetExpirable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpirable'
type MockNoProviderStore_SetExpirable_Call struct {
	*mock.Call
}

// SetExpirable is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - expires bool
func (_e *MockNoProviderStore_Expecter) SetExpirable(ctx interface{}, key interface{}, expires interface{}) *MockNoProviderStore_SetExpirable_Call {
	return &MockNoProviderStore_SetExpirable_Call{Call: _e.mock.On("SetExpirable", ctx, key, expires)}
}

func (_c *MockNoProviderStore_SetExpirable_Call) Run(run func(ctx context.Context, key multihash.Multihash, expires bool)) *MockNoProviderStore_SetExpirable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash), args[2].(bool))
	})
	return _c
}

func (_c *MockNoProviderStore_SetExpirable_Call) Return(_a0 error) *MockNoProviderStore_SetExpirable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNoProviderStore_SetExpirable_Call) RunAndReturn(run func(context.Context, multihash.Multihash, bool) error) *MockNoProviderStore_SetExpirable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNoProviderStore creates a new instance of MockNoProviderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoProviderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoProviderStore {
	mock := &MockNoProviderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
