// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package types

import (
	"context"

	"github.com/multiformats/go-multicodec"
	"github.com/multiformats/go-multihash"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNoProviderStore creates a new instance of MockNoProviderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoProviderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoProviderStore {
	mock := &MockNoProviderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoProviderStore is an autogenerated mock type for the NoProviderStore type
type MockNoProviderStore struct {
	mock.Mock
}

type MockNoProviderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoProviderStore) EXPECT() *MockNoProviderStore_Expecter {
	return &MockNoProviderStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockNoProviderStore
func (_mock *MockNoProviderStore) Add(ctx context.Context, key multihash.Multihash, values ...multicodec.Code) (uint64, error) {
	// multicodec.Code
	_va := make([]interface{}, len(values))
	for _i := range values {
		_va[_i] = values[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, ...multicodec.Code) (uint64, error)); ok {
		return returnFunc(ctx, key, values...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, ...multicodec.Code) uint64); ok {
		r0 = returnFunc(ctx, key, values...)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, multihash.Multihash, ...multicodec.Code) error); ok {
		r1 = returnFunc(ctx, key, values...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoProviderStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockNoProviderStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - values ...multicodec.Code
func (_e *MockNoProviderStore_Expecter) Add(ctx interface{}, key interface{}, values ...interface{}) *MockNoProviderStore_Add_Call {
	return &MockNoProviderStore_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx, key}, values...)...)}
}

func (_c *MockNoProviderStore_Add_Call) Run(run func(ctx context.Context, key multihash.Multihash, values ...multicodec.Code)) *MockNoProviderStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		var arg2 []multicodec.Code
		variadicArgs := make([]multicodec.Code, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(multicodec.Code)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNoProviderStore_Add_Call) Return(v uint64, err error) *MockNoProviderStore_Add_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockNoProviderStore_Add_Call) RunAndReturn(run func(ctx context.Context, key multihash.Multihash, values ...multicodec.Code) (uint64, error)) *MockNoProviderStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type MockNoProviderStore
func (_mock *MockNoProviderStore) Members(ctx context.Context, key multihash.Multihash) ([]multicodec.Code, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []multicodec.Code
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash) ([]multicodec.Code, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash) []multicodec.Code); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]multicodec.Code)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, multihash.Multihash) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNoProviderStore_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type MockNoProviderStore_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
func (_e *MockNoProviderStore_Expecter) Members(ctx interface{}, key interface{}) *MockNoProviderStore_Members_Call {
	return &MockNoProviderStore_Members_Call{Call: _e.mock.On("Members", ctx, key)}
}

func (_c *MockNoProviderStore_Members_Call) Run(run func(ctx context.Context, key multihash.Multihash)) *MockNoProviderStore_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNoProviderStore_Members_Call) Return(codes []multicodec.Code, err error) *MockNoProviderStore_Members_Call {
	_c.Call.Return(codes, err)
	return _c
}

func (_c *MockNoProviderStore_Members_Call) RunAndReturn(run func(ctx context.Context, key multihash.Multihash) ([]multicodec.Code, error)) *MockNoProviderStore_Members_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpirable provides a mock function for the type MockNoProviderStore
func (_mock *MockNoProviderStore) SetExpirable(ctx context.Context, key multihash.Multihash, expires bool) error {
	ret := _mock.Called(ctx, key, expires)

	if len(ret) == 0 {
		panic("no return value specified for SetExpirable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, multihash.Multihash, bool) error); ok {
		r0 = returnFunc(ctx, key, expires)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNoProviderStore_SetExpirable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpirable'
type MockNoProviderStore_SetExpirable_Call struct {
	*mock.Call
}

// SetExpirable is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - expires bool
func (_e *MockNoProviderStore_Expecter) SetExpirable(ctx interface{}, key interface{}, expires interface{}) *MockNoProviderStore_SetExpirable_Call {
	return &MockNoProviderStore_SetExpirable_Call{Call: _e.mock.On("SetExpirable", ctx, key, expires)}
}

func (_c *MockNoProviderStore_SetExpirable_Call) Run(run func(ctx context.Context, key multihash.Multihash, expires bool)) *MockNoProviderStore_SetExpirable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].(multihash.Multihash)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNoProviderStore_SetExpirable_Call) Return(err error) *MockNoProviderStore_SetExpirable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNoProviderStore_SetExpirable_Call) RunAndReturn(run func(ctx context.Context, key multihash.Multihash, expires bool) error) *MockNoProviderStore_SetExpirable_Call {
	_c.Call.Return(run)
	return _c
}
