// Code generated by mockery v2.53.3. DO NOT EDIT.

package types

import (
	context "context"

	model "github.com/ipni/go-libipni/find/model"
	mock "github.com/stretchr/testify/mock"

	multihash "github.com/multiformats/go-multihash"
)

// MockProviderStore is an autogenerated mock type for the ProviderStore type
type MockProviderStore struct {
	mock.Mock
}

type MockProviderStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderStore) EXPECT() *MockProviderStore_Expecter {
	return &MockProviderStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, key, values
func (_m *MockProviderStore) Add(ctx context.Context, key multihash.Multihash, values ...model.ProviderResult) (uint64, error) {
	_va := make([]interface{}, len(values))
	for _i := range values {
		_va[_i] = values[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash, ...model.ProviderResult) (uint64, error)); ok {
		return rf(ctx, key, values...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash, ...model.ProviderResult) uint64); ok {
		r0 = rf(ctx, key, values...)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, multihash.Multihash, ...model.ProviderResult) error); ok {
		r1 = rf(ctx, key, values...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockProviderStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - values ...model.ProviderResult
func (_e *MockProviderStore_Expecter) Add(ctx interface{}, key interface{}, values ...interface{}) *MockProviderStore_Add_Call {
	return &MockProviderStore_Add_Call{Call: _e.mock.On("Add",
		append([]interface{}{ctx, key}, values...)...)}
}

func (_c *MockProviderStore_Add_Call) Run(run func(ctx context.Context, key multihash.Multihash, values ...model.ProviderResult)) *MockProviderStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.ProviderResult, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(model.ProviderResult)
			}
		}
		run(args[0].(context.Context), args[1].(multihash.Multihash), variadicArgs...)
	})
	return _c
}

func (_c *MockProviderStore_Add_Call) Return(_a0 uint64, _a1 error) *MockProviderStore_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderStore_Add_Call) RunAndReturn(run func(context.Context, multihash.Multihash, ...model.ProviderResult) (uint64, error)) *MockProviderStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Batch provides a mock function with no fields
func (_m *MockProviderStore) Batch() ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Batch")
	}

	var r0 ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]
	if rf, ok := ret.Get(0).(func() ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult])
		}
	}

	return r0
}

// MockProviderStore_Batch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Batch'
type MockProviderStore_Batch_Call struct {
	*mock.Call
}

// Batch is a helper method to define mock.On call
func (_e *MockProviderStore_Expecter) Batch() *MockProviderStore_Batch_Call {
	return &MockProviderStore_Batch_Call{Call: _e.mock.On("Batch")}
}

func (_c *MockProviderStore_Batch_Call) Run(run func()) *MockProviderStore_Batch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProviderStore_Batch_Call) Return(_a0 ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]) *MockProviderStore_Batch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderStore_Batch_Call) RunAndReturn(run func() ValueSetCacheBatcher[multihash.Multihash, model.ProviderResult]) *MockProviderStore_Batch_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function with given fields: ctx, key
func (_m *MockProviderStore) Members(ctx context.Context, key multihash.Multihash) ([]model.ProviderResult, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []model.ProviderResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) ([]model.ProviderResult, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) []model.ProviderResult); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProviderResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, multihash.Multihash) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderStore_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type MockProviderStore_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
func (_e *MockProviderStore_Expecter) Members(ctx interface{}, key interface{}) *MockProviderStore_Members_Call {
	return &MockProviderStore_Members_Call{Call: _e.mock.On("Members", ctx, key)}
}

func (_c *MockProviderStore_Members_Call) Run(run func(ctx context.Context, key multihash.Multihash)) *MockProviderStore_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash))
	})
	return _c
}

func (_c *MockProviderStore_Members_Call) Return(_a0 []model.ProviderResult, _a1 error) *MockProviderStore_Members_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderStore_Members_Call) RunAndReturn(run func(context.Context, multihash.Multihash) ([]model.ProviderResult, error)) *MockProviderStore_Members_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpirable provides a mock function with given fields: ctx, key, expires
func (_m *MockProviderStore) SetExpirable(ctx context.Context, key multihash.Multihash, expires bool) error {
	ret := _m.Called(ctx, key, expires)

	if len(ret) == 0 {
		panic("no return value specified for SetExpirable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash, bool) error); ok {
		r0 = rf(ctx, key, expires)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProviderStore_SetExpirable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpirable'
type MockProviderStore_SetExpirable_Call struct {
	*mock.Call
}

// SetExpirable is a helper method to define mock.On call
//   - ctx context.Context
//   - key multihash.Multihash
//   - expires bool
func (_e *MockProviderStore_Expecter) SetExpirable(ctx interface{}, key interface{}, expires interface{}) *MockProviderStore_SetExpirable_Call {
	return &MockProviderStore_SetExpirable_Call{Call: _e.mock.On("SetExpirable", ctx, key, expires)}
}

func (_c *MockProviderStore_SetExpirable_Call) Run(run func(ctx context.Context, key multihash.Multihash, expires bool)) *MockProviderStore_SetExpirable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash), args[2].(bool))
	})
	return _c
}

func (_c *MockProviderStore_SetExpirable_Call) Return(_a0 error) *MockProviderStore_SetExpirable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderStore_SetExpirable_Call) RunAndReturn(run func(context.Context, multihash.Multihash, bool) error) *MockProviderStore_SetExpirable_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderStore creates a new instance of MockProviderStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderStore {
	mock := &MockProviderStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
