// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ipni/go-libipni/find/model"
	mock "github.com/stretchr/testify/mock"

	multihash "github.com/multiformats/go-multihash"
)

// MockFinder is an autogenerated mock type for the Finder type
type MockFinder struct {
	mock.Mock
}

type MockFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinder) EXPECT() *MockFinder_Expecter {
	return &MockFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *MockFinder) Find(_a0 context.Context, _a1 multihash.Multihash) (*model.FindResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *model.FindResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) (*model.FindResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multihash.Multihash) *model.FindResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FindResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, multihash.Multihash) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 multihash.Multihash
func (_e *MockFinder_Expecter) Find(_a0 interface{}, _a1 interface{}) *MockFinder_Find_Call {
	return &MockFinder_Find_Call{Call: _e.mock.On("Find", _a0, _a1)}
}

func (_c *MockFinder_Find_Call) Run(run func(_a0 context.Context, _a1 multihash.Multihash)) *MockFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multihash.Multihash))
	})
	return _c
}

func (_c *MockFinder_Find_Call) Return(_a0 *model.FindResponse, _a1 error) *MockFinder_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFinder_Find_Call) RunAndReturn(run func(context.Context, multihash.Multihash) (*model.FindResponse, error)) *MockFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFinder creates a new instance of MockFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinder {
	mock := &MockFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
