// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// MockQueryAPIClient is an autogenerated mock type for the QueryAPIClient type
type MockQueryAPIClient struct {
	mock.Mock
}

type MockQueryAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryAPIClient) EXPECT() *MockQueryAPIClient_Expecter {
	return &MockQueryAPIClient_Expecter{mock: &_m.Mock}
}

// Query provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockQueryAPIClient) Query(_a0 context.Context, _a1 *dynamodb.QueryInput, _a2 ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *dynamodb.QueryOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) *dynamodb.QueryOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.QueryOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueryAPIClient_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockQueryAPIClient_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *dynamodb.QueryInput
//   - _a2 ...func(*dynamodb.Options)
func (_e *MockQueryAPIClient_Expecter) Query(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockQueryAPIClient_Query_Call {
	return &MockQueryAPIClient_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockQueryAPIClient_Query_Call) Run(run func(_a0 context.Context, _a1 *dynamodb.QueryInput, _a2 ...func(*dynamodb.Options))) *MockQueryAPIClient_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*dynamodb.QueryInput), variadicArgs...)
	})
	return _c
}

func (_c *MockQueryAPIClient_Query_Call) Return(_a0 *dynamodb.QueryOutput, _a1 error) *MockQueryAPIClient_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueryAPIClient_Query_Call) RunAndReturn(run func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)) *MockQueryAPIClient_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryAPIClient creates a new instance of MockQueryAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryAPIClient {
	mock := &MockQueryAPIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
