name: Terraform

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      workspace:
        required: true
        type: string
      did:
        required: true
        type: string
      apply:
        required: true
        type: boolean
    secrets:
      aws-account-id:
        required: true
      aws-region:
        required: true
      private-key:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCOUNT_ID: ${{ secrets.aws-account-id }}
  AWS_REGION: ${{ secrets.aws-region }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: arn:aws:iam::${{ secrets.aws-account-id }}:role/terraform-ci

      - uses: opentofu/setup-opentofu@v1
      - uses: actions/setup-go@v5

      - name: Set Environment Variables
        run: |
          echo "ENV=${{ inputs.env }}" >> $GITHUB_ENV
          echo "TF_WORKSPACE=${{ inputs.workspace }}" >> $GITHUB_ENV
          echo "TF_VAR_private_key=${{ secrets.private-key }}" >> $GITHUB_ENV
          echo "TF_VAR_did=${{ inputs.did }}" >> $GITHUB_ENV

      - name: Tofu Init
        run: |
          tofu -chdir="deploy/app" init

      - name: Build Go Apps
        run: |
          touch .env
          make lambdas

      - name: Terraform Plan
        if: ${{ !inputs.apply }}
        run: |
          tofu -chdir="deploy/app" plan

      - name: Terraform Apply
        if: ${{ inputs.apply }}
        run: |
          tofu -chdir="deploy/app" apply -input=false --auto-approve
